site_name: 'bioimageio-collection'
site_url: 'https://bioimage-io.github.io/collection'
site_author: Fynn Beuttenmüller
site_description: 'BioImage.IO Partner Compatibility checks and collection backoffice.'

repo_name: bioimage-io/collection
repo_url: https://github.com/bioimage-io/collection
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  # features:
  #   - announce.dismiss
  #   - content.action.edit
  #   - content.action.view
  #   - content.code.annotate
  #   - content.code.copy
  #   # - content.code.select
  #   # - content.footnote.tooltips
  #   # - content.tabs.link
  #   - content.tooltips
  #   # - header.autohide
  #   # - navigation.expand
  #   - navigation.footer
  #   - navigation.indexes
  #   # - navigation.instant
  #   # - navigation.instant.prefetch
  #   # - navigation.instant.progress
  #   # - navigation.prune
  #   - navigation.sections
  #   - navigation.tabs
  #   # - navigation.tabs.sticky
  #   - navigation.top
  #   - navigation.tracking
  #   - search.highlight
  #   - search.share
  #   - search.suggest
  #   - toc.follow
  #   # - toc.integrate

  palette:
    - media: '(prefers-color-scheme)'
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-auto
        name: 'Switch to light mode'
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-7
        name: 'Switch to dark mode'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: 'Switch to system preference'

  font:
    text: Roboto
    code: Roboto Mono

  logo: https://raw.githubusercontent.com/bioimage-io/bioimage.io/refs/heads/gh-pages/img/bioimage-io-icon.png
  favicon: https://raw.githubusercontent.com/bioimage-io/bioimage.io/refs/heads/gh-pages/icons/favicon.ico

plugins:
  - autorefs
  - coverage:
      html_report_dir: htmlcov
  - markdown-exec
  - mkdocstrings:
      handlers:
        python:
          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ['!^_']
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            extensions:
              - griffe_pydantic:
                  schema: true
  - search
  - section-index
  # - api-autonav:
  #     modules: ['src/backoffice']
  #     module_options:
  #       '.*':
  #         show_submodules: true
  #         docstring_style: google
  #         show_signature: true
  #         heading_level: 1
  #         show_symbol_type_heading: true

# markdown_extensions:
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
markdown_extensions:
  - attr_list
  - admonition
  - callouts:
      strip_period: false
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: '¤'
nav:
  - Home: index.md
  - API Reference: api.md
  - Compatibility Reports: reports_overview.md
  - Changelog: changelog.md
  - Coverage report: coverage.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bioimage-io
  version:
    provider: mike
